export const CONTRACT_ADDRESSES = {
  BROILER_TOKEN: process.env.NEXT_PUBLIC_BROILER_TOKEN_ADDRESS,
  WMATIC: process.env.NEXT_PUBLIC_WMATIC_ADDRESS,
  HOPE_NOBT_TOKEN: process.env.NEXT_PUBLIC_HOPE_NOBT_TOKEN_ADDRESS,
  HOPE_NOBT_DISTRIBUTOR: process.env.NEXT_PUBLIC_HOPE_NOBT_DISTRIBUTOR_ADDRESS,
  BRT_WMATIC_LP: process.env.NEXT_PUBLIC_BRT_WMATIC_LP_ADDRESS,
};